apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nornos

resources:
- namespace.yaml
- patient-app/deployment.yaml
- doctor-app/deployment.yaml
- agent-service/deployment.yaml
- relay-server/deployment.yaml
- shared-data-server/deployment.yaml
- auth-service/deployment.yaml
- vault-server/deployment.yaml
- ingress.yaml
- network-policies.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: nornos
